### ISSUE TITLE
[Docs] [Docs I/A] Apply design refresh to global header

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/gatsby-theme-newrelic#510]
## Summary

Apply design refresh to global header.

### Design Questions 

- [x] Verify mobile exp.
- [x] confirm dark mode color 
- [x] where do the dark mode / light mode toggle docs 
- [x] What should the language toggle look like?
- [x] What is the final version of the header we need to build?
- [x] Remove adding background color for current site in menu of sites?
- [x] Header mobile nav menu: does the main menu go away or where should it be displayed on mobile? 

## Design

Changes include:
- increase height to 72px (verify with design mock)
- always that darker charcoal color
- search input is lighter so it's more visible
- free account and login button style changes

**Figma**
[Desktop (light mode)](https://www.figma.com/proto/0jsTPLtwz6Bljndkbr1COn/open-source-DS-%5BWIP%5D?page-id=56%3A39509&node-id=150%3A52221&viewport=501%2C48%2C1.05&scaling=min-zoom&starting-point-node-id=150%3A52221&show-proto-sidebar=1)

![2021-11-09_09-16-22](https://user-images.githubusercontent.com/2952843/140973759-3864a432-3c4f-4be8-894f-3be17d397c5a.png)

[Mobile](https://www.figma.com/proto/0jsTPLtwz6Bljndkbr1COn/open-source-DS-%5BWIP%5D?page-id=141%3A43127&node-id=141%3A43617&viewport=501%2C48%2C1.01&scaling=scale-down&starting-point-node-id=141%3A43617)

## Acceptance criteria
- [x] Header height is increased to 72px (verify w/design mock)
- [x] Header color is always dark, charcoal color
- [x] Search input is lighter (per design spec) color, placeholder text updated
- [x] dark/light mode toggle is larger
- [x] Free account and login button styles updated
- [x] Current site background color style changes per spec
- [x] Mobile header updated per design spec

## Helpful links

**Comment by jpvajda** [comment]
@roadlittledawn thought by end of this week, this design may be finalized.

**Comment by jpvajda** [comment]
@roadlittledawn will prepare this ticket for the team

**Comment by roadlittledawn** [comment]
re: main menu in header. should stay the same. scrollable left/right on smaller desktop screens. does not display on mobile. but this is on Àngel's radar for a full fledged redesign of navbar in the future.

**Comment by legnaleama** [comment]
@jpvajda @roadlittledawn A couple of notes on the requirements:

*Buttons*
I'm the process of overhauling and documenting all button styles. If this is confusing we can use the current styles for now and leave the update of styling for a separate task.

*Icons*
I was unaware of the usage of a specific icon library at the time of creating the mockup, Eva is just an Open Source library I used in the past as a good starting point for a decent UX icon library. That said, I've been checking Feather and organising their icons in groups and for the most part it looks really robust except for a few fixes I had to apply to the vectors (probably due to random conversions while downloading using their customisation UI though).

I'm fine keeping Feather for now and reviewing in the future when I had a bit more time to play with them and put them to the test. 

Finally, I'd be open to discussing what's the best workflow around icons when thinking of a more systematic approach from both Design and Frontend. 

I'm attaching a comparison between the 3 libraries just for context.
![image](https://user-images.githubusercontent.com/3636549/141343593-e80b7771-1cbf-43b3-baca-a34e36879fb7.png)

**Comment by jpvajda** [comment]
These seems so similar.. OneCore is used for cases where we need very specific New Relic only icons , but Feather and Eva seem like the same library. happy to talk more about it but it sounds like for now we are ok holding off introducing any new icon libraries.
