### ISSUE TITLE
GlobalHeader is cut off by overflow:hidden on narrow viewports

### ISSUE THREAD

**Issue by tyreer** [newrelic/gatsby-theme-newrelic#79]
## Description

In mobile or narrow viewports, the `GlobalHeader` nav is being cut off in the middle of a nav item.

![IMG_2137](https://user-images.githubusercontent.com/20293876/90313084-89ea0c80-df01-11ea-9aaf-5af51ff3f72d.jpg)

Screen shot from iPhone 8, Safari browser, iOS 13.6.1

## Steps to Reproduce

- Load https://developer.newrelic.com/ on a mobile device or in Chrome using the iPhone 6/7/8 device emulator on via dev tools
- Note in the upper right hand corner the word _Community_ is cut off and the remaining nav items are not accessible

## Expected Behaviour

Good question! I suppose I'd expect this either:
1. to have a horizontal scroll
1. to have only 2–3 items selectable, which all fit as full text
1. to have a hamburger-icon and a mobile nav

Since most of the pages using this header will already have their own site-specific hamburger nav, you can probably rule our number 3. 

## Your Environment

- iPhone 8, Safari browser, iOS 13.6.1

## Additional context

- I came across this while working through this open ticket on the Open Source site repo: https://github.com/newrelic/opensource-website/issues/556
- This `overfill: hidden` rule seems related: https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/GlobalHeader.js#L79

**Comment by jerelmiller** [comment]
Hey @tyreer! Funny you open this issue because I also spotted the same thing. I just opened a PR (#78) yesterday that should address this by making the site links scrollable. We are adding a sign up link to the global header and I figured it would be a good time to fix this. I'll link this issue to that PR so you can keep track of when this goes live! (likely sometime Monday) Thanks so much for reporting this!

**Comment by tyreer** [comment]
Nice one @jerelmiller! That PR looks like it'll address this nicely.
